"""
Financial Intelligence OS (FIOS)
Blueprint Validator

Milestone 3 - Validation Platform

Validates Builder blueprint documents.
"""

from __future__ import annotations

from pathlib import Path

from .validation_manager import ValidationResult


class BlueprintValidator:
    """
    Validates blueprint documentation generated by the Builder.
    """

    def __init__(self, blueprint_files: list[Path]) -> None:
        self.blueprint_files = blueprint_files

    def validate(self) -> ValidationResult:
        """
        Validate that blueprint documents exist and are not empty.
        """
        issues: list[str] = []

        for blueprint in self.blueprint_files:

            if not blueprint.exists():
                issues.append(f"{blueprint} (missing)")
                continue

            if blueprint.stat().st_size == 0:
                issues.append(f"{blueprint} (empty)")

        if issues:
            return ValidationResult(
                name="Blueprint Validator",
                passed=False,
                message="Issues found: " + ", ".join(issues),
            )

        return ValidationResult(
            name="Blueprint Validator",
            passed=True,
            message="All blueprint documents are valid.",
        )